name: Nix Update Command
on:
  issue_comment:
    types:
      - created
      - edited

concurrency: nix-update-${{ github.event.issue.number }}

jobs:
  command:
    if: "github.event.comment.body == '/nix-update' && github.event.issue.pull_request"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Checkout Self
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: refs/heads/${{ github.event.repository.default_branch }}

      - name: Check if user is allowed to run the command
        shell: bash
        id: perms
        run: |
          echo '${{ toJSON(github) }}' > /tmp/context.json
          if nix eval --expr 'import ./.github/allowed-nix-update-users.nix (builtins.fromJSON (builtins.readFile /tmp/context.json))' --impure; then
            echo "allowed=true" >> "$GITHUB_OUTPUT"
          else
            echo "allowed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Add no permission reacton
        if: "${{ steps.perms.outputs.allowed == 'false' }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '-1'

      - name: Add okay reaction
        if: "${{ steps.perms.outputs.allowed }}"
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - id: get-branch
        if: "${{ steps.perms.outputs.allowed }}"
        name: Get PR branch
        run: echo "branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> "$GITHUB_OUTPUT"
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout PR
        if: "${{ steps.perms.outputs.allowed }}"
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get-branch.outputs.branch }}

      - name: Update Nix Files
        if: "${{ steps.perms.outputs.allowed }}"
        run: nix develop --impure .#ci --command "update-nix-package-deps"

      - name: Commit and Push changes
        if: "${{ steps.perms.outputs.allowed }}"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git user
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if any changes were made
          if [[ ! -z $(git status -s) ]]; then
            git commit -a -F - <<EOF
          nix: Update generated files

          This commit was automatically generated by [this workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
          EOF

            git push
            gh pr comment ${{ github.event.issue.number }} -F - <<EOF
          Successfully updated generated nix files! 🚀

          Run triggered by @${{ github.event.sender.login }} (${{ github.event.comment.html_url }})
          EOF
          else
            gh pr comment ${{ github.event.issue.number }} -F - <<EOF
          Generated files are up to date! 👌

          Run triggered by @${{ github.event.sender.login }} (${{ github.event.comment.html_url }})
          EOF
          fi
